### ISSUE TITLE
Where is defined the image property

### ISSUE THREAD

**Issue by fredleput** [jbouzekri/FileUploaderBundle#1]
Hi,

I try to define the image property in my entity how to ?

**Comment by jbouzekri** [comment]
Hi,

Oups I forgot in my documentation to explain how to bind the uploaded file with the entity. I will add it tonight.

You must create an attribute type text : 

``` php
/**
 * @ORM\Column(type="string", length=255, nullable=true)
 * @var string
 */
protected $picture;
```

Then in your form you can add the field type image ajax : 

``` php
$builder->add('picture', 'jb_image_ajax', array(
    'endpoint' => 'my_endpoint_name',
    'img_width' => 100
));
```

Note that the filename will be stored in DB. Then using the table file_history, we can retrieve the endpoint used to upload it and so find it in the file storage in order to generate an url.

What is missing is a custom validator to be sure that somebody else cannot submit an existing filename owned by another user. I am going to add it this weekend.

I am waiting for your feedback.

**Comment by fredleput** [comment]
thx try thathis and go back...

**Comment by fredleput** [comment]
Sorry, i have an entity Location in which i have the property image (string) with getter and setter.
in my LocationType i have :
$builder
            ->add('categorie')
            ->add('proprietaire')
            ->add('adr1')
            ->add('adr2')
            ->add('cp')
            ->add('ville')
            ->add('situation')
            ->add('ouverture')
            ->add('capacite')
            ->add('savplus')
            ->add('classe')
            ->add('classement')
            ->add('actif')
            ->add('site')
            ->add('image', 'jb_image_ajax', array(
                'img_width' => 400,
                'endpoint' => 'gallery'
            ))
        ;
and i have the following error :

Catchable Fatal Error: Argument 1 passed to Jb\Bundle\FileUploaderBundle\Service\FileHistoryManager::getUrl() must be an instance of Jb\Bundle\FileUploaderBundle\Entity\FileHistory, null given

**Comment by jbouzekri** [comment]
It seems you have form data in your field `image` (lookup the hidden input text in the field HTML or var_dump($form->getData()) in controller after isValid) but you don't have the FileHistory entry matching this filename in the table `jb_filehistory`. Could you check this ?

I will add check for this case this evening.

**Comment by fredleput** [comment]
"but you don't have the FileHistory entry matching this filename in the table jb_filehistory"
No indeed ther's no relation between this tables but there should have one bettween image property and a fileHistory entry ?

**Comment by jbouzekri** [comment]
You don't really need the doctrine relation. It would be a security for consistency but usually when uploading the image using the ajax route, the entry with uploaded file original name, generated name and endpoint used should be created in the table. If it didn't, you maybe have a php error somewhere when the uploaded the file.

Does the table `jb_filehistory` exists ? (have you runned the d:s:u command ?)

**Comment by fredleput** [comment]
Yes the table jb_filehistory exists whith 4 fields.
What the d:s:u command ?

Sorry i'm a noob but where can i find the result of var_dump($form->getData()) since i get this error

**Comment by jbouzekri** [comment]
You have content in there ?

d:s:u is a shortcut for doctrine:schema:update.

In your action of your controller, you should have something like this : 

``` php
if ($form->isValid()) {
  // Add the var_dump to see what you have in your form after submit
   var_dump( $form->getData());die();
}
```

Your error occured because you have data in the image field (maybe because the field already existed before adding this bundle or because you uploaded a picture but an error occured on upload when trying to create the entry in file history) and when we search the file history table for the entry corresponding to the data it does not find it.

**Comment by fredleput** [comment]
You're right the field image already existed. I change it's name to picture (getter and setter also). In my Location type i change the field image to picture. i update my database (d:s:u --force). All is alright. I clear the cache. i retry and still get the same error.

i can't submit the form since i get the error when it should appear so the var_dump isn't executed...

I have no content in jb_filehistory table...

**Comment by jbouzekri** [comment]
No what I mean is that : do you have existing data in this field image/picture ?

**Comment by fredleput** [comment]
No there's nothing in it

**Comment by jbouzekri** [comment]
Nothing as NULL or empty string "" ?

**Comment by fredleput** [comment]
empty string i think i can update my DB to put it at NULL

**Comment by jbouzekri** [comment]
Yeah, do that and it should work

**Comment by fredleput** [comment]
Yes that's it after update my DB the form appears

**Comment by fredleput** [comment]
Sorry, but now i have this error "unknown resolver". A configuration problem i think...

**Comment by jbouzekri** [comment]
Yeah, look at the getting started page : https://github.com/jbouzekri/FileUploaderBundle/blob/master/Resources/doc/base/getting_started.md

You have a full configuration for the jb_image_ajax field type to work.

Resolver is configured in jb_file_uploader. You should have a resolver which match the gaufrette filesystem used in the oneup configuration.

I tested it 2 days ago and normally this configuration in getting started works as it is. You can copy paste it. Create a folder web/uploads. Give apache read and write rights on web/uploads, clear cache and go.

I am waiting for your feedback if you have any issue or misunderstanding.

**Comment by fredleput** [comment]
my folder web/uploads is writable for www-data group
I think i copy / paste this configuration from the getting started section :

``` yml
#oneup_uploader
oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp

#liip_imagine
liip_imagine:
    filter_sets:
        original: ~

twig:
    form:
        resources:
            - 'JbFileUploaderBundle:Form:fields.html.twig'

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image:
            local:
                directory: %kernel.root_dir%/../web/uploads
                create: true
    filesystems:
        image:
            adapter: image
            alias: image_filesystem

oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp
            storage:
                type: gaufrette
                filesystem: gaufrette.image_filesystem
                stream_wrapper: gaufrette://image/

liip_imagine:
    loaders:
        stream.image_filesystem:
            stream:
                wrapper: gaufrette://image/
    filter_sets:
        original: ~
        thumb_from_original:
            data_loader: stream.image_filesystem
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }

jb_file_uploader:
    resolvers:
        upload:
            assets:
                directory: uploads
    endpoints:
        gallery:
            upload_resolver: upload
            upload_validators: {}
            crop_validators: {}
```

**Comment by jbouzekri** [comment]
Remove this : 

``` yml
#oneup_uploader
oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp

#liip_imagine
liip_imagine:
    filter_sets:
        original: ~

twig:
    form:
        resources:
            - 'JbFileUploaderBundle:Form:fields.html.twig'
```

In `app/config.yml`, you have the following line somewhere : 

``` yml
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
```

Modify it as : 

``` yml
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
     form:
        resources:
            - 'JbFileUploaderBundle:Form:fields.html.twig'
```

And clear cache. What does happen ? Always the unkown resolver problem ?

**Comment by fredleput** [comment]
Sorry but yes. Thx for help ! I will go eating its 12:22 in France and i come back this afternoon.

**Comment by jbouzekri** [comment]
Je suis français également si tu veux discuter dans cette langue. Aucun problème.

**Comment by fredleput** [comment]
En effet ça sera plus facile ce qui est étonnant c'est que le fichier est uploadé. Je le retrouve dans mon dossier web/uploads ??? la table jb_filehistory se remplit... Par contre je n'ai rien dans la table de mon entité.

**Comment by fredleput** [comment]
Bon appétit à tout, :+1:

**Comment by jbouzekri** [comment]
Oui c'est normal. Ce qu'il se passe, c'est que l'upload se passe bien. Tu dois avoir le fichier avec un nom à plusieurs caractères aléatoire et son extension. L'erreur intervient lorsque le bundle essaye de générer une url pour l'affichage dans le cadre de preview.

Il cherche à utiliser un resolver vide. Quand tu as renommé to champ en picture et que tu as modifié ton FormType, tu as copié le code indiqué dans mon premier commentaire tel quel : 

``` php
$builder->add('picture', 'jb_image_ajax', array(
    'endpoint' => 'my_endpoint_name',
    'img_width' => 100
));
```

Si c'est le cas alors c'est normal que ça plante. Tu dis à ce champ de formulaire d'utiliser le endpoint `my_endpoint_name` mais quand tu regardes la configuration du getting started, tu as configuré un unique endpoint `gallery` (cf la configuration oneup_uploader.mappings où tu as une clé gallery et  jb_file_uploader.endpoints où tu retrouves cette clé gallery).

Peux tu modifier la configuration de ton formulaire ainsi : 

``` php
$builder->add('picture', 'jb_image_ajax', array(
    'endpoint' => 'gallery',
    'img_width' => 100
));
```

Et surtout reprendre ton process du début : champ de formulaire vide, upload d'une nouvelle image, ...

**Comment by fredleput** [comment]
Re...
En fait la config du endpoint est OK "gallery" partout...

**Comment by jbouzekri** [comment]
Peux tu m'indiquer ce que tu as dans la table file_history ?

**Comment by fredleput** [comment]
file_name 54b7bd4e64282.jpg
original_name   bernard-omnes.jpg 
type    gallery
user_id     1

**Comment by jbouzekri** [comment]
Et 54b7bd4e64282.jpg est bien le dernier fichier que tu as uploadé ?

Tu peux essayer un truc ?

Modifier la configuration : 

``` yml
jb_file_uploader:
    resolvers:
        upload:
            assets:
                directory: uploads
    upload_resolver: upload
    endpoints:
        gallery:
            upload_validators: {}
            crop_validators: {}
```
